<div class="tracy-inner tracy-InfoPanel">
    <div class="tracy-inner-container">
        <h1>Global translations</h1>
        <table>
			<?php foreach ($this->translator->getTranslations('') as $translation): ?>
                <tr><th><?= $translation->label ?></th><td><?= $translation->getPK() ?></td></tr>
			<?php endforeach ?>
        </table>
        <br>
        <h1>Untranslated (<span style="color: red;"><?= \count($this->translator->getCurrentUntranslated()) ?></span>)</h1>
        <table>
            <thead>
            <th>Label</th>
            <th>ID</th>
            </thead>
            <tbody>
			<?php foreach ($this->translator->getCurrentUntranslated() as $id => $label): ?>
                <tr>
                    <td><?= $label ?></td>
                    <td><?= $id ?></td>
                </tr>
			<?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>