<div class="tracy-inner tracy-InfoPanel">
    <div class="tracy-inner-container">
        <h1>Available mutations</h1>
        <table>
            <thead>
            <th>Name</th>
            <th>Prefix</th>
            </thead>
            <tbody>
			<?php foreach ($this->translator->getAvailableMutations() as $key => $value): ?>
                <tr>
					<?php if ($key == $this->translator->getMutation()): ?>
                        <td>
                            <b><?= $key ?></b>
                        </td>
                        <td>
                            <b><?= $value ?></b>
                        </td>
					<?php else: ?>
                        <td>
                            <?= $key ?>
                        </td>
                        <td>
                            <?= $value ?>
                        </td>
					<?php endif; ?>

                </tr>
			<?php endforeach ?>
            </tbody>
        </table>
    </div>
    <div class="tracy-inner-container">
        <h1>Untranslated</h1>
        <h2>Total: <?= $this->translator->getUntranslatedCount() ?></h2>
        <table>
            <thead>
            <th>String</th>
            <th>Count</th>
            </thead>
            <tbody>
			<?php foreach ($this->translator->getUntranslated() as $key => $value): ?>
                <tr>
                    <td><?= $key ?></td>
                    <td><?= $value ?></td>
                </tr>
			<?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>